# Generated by Django 4.1.1 on 2022-09-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=200)),
                ('rental_rate', models.IntegerField(default=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('tips', models.IntegerField(default=0)),
                ('costs', models.IntegerField(default=0)),
                ('deposit', models.IntegerField(default=0)),
                ('fines', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('tax', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.week')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('tip', models.IntegerField(default=0, verbose_name='Чаевые')),
                ('cash', models.BooleanField(default=False, verbose_name='За наличные')),
                ('toll', models.IntegerField(default=0, verbose_name='ЗСД')),
                ('save_tax', models.BooleanField(default=False, verbose_name='С покупкой смены')),
                ('saved_tax_result', models.IntegerField(default=0, verbose_name='Экономия комиссии')),
                ('tax_result', models.IntegerField(default=0, verbose_name='Сумма доп.комиссии')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car', verbose_name='Авто')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver', verbose_name='Водитель')),
                ('extra_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.extratax', verbose_name='Режим доп.комиссии')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shift', verbose_name='День')),
            ],
        ),
        migrations.CreateModel(
            name='PlanShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shift')),
                ('plan_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
            ],
        ),
    ]
